WvError: create a WvErr type alias for WvError.
I'm starting to think that WvError is getting common enough that a shorter
name makes sense.  Plus, I want to introduce a WvErrStack object, and
WvErrorStack just seems unnecessarily long.